{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"Untitled7.ipynb","provenance":[],"mount_file_id":"15_-1wo2IDtqTJh8tEGmcS2U6S2IkJxnD","authorship_tag":"ABX9TyPjTgtGw9fBFknrRyAdNOUE"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"28AnD5O0aWsj","executionInfo":{"status":"ok","timestamp":1648620945230,"user_tz":-330,"elapsed":530,"user":{"displayName":"Akash Sri","userId":"07595179456817660778"}},"outputId":"c03ce522-f528-443e-fae1-e2b10e258ca1"},"outputs":[{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/bin/kaggle\", line 5, in <module>\n","    from kaggle.cli import main\n","  File \"/usr/local/lib/python3.7/dist-packages/kaggle/__init__.py\", line 23, in <module>\n","    api.authenticate()\n","  File \"/usr/local/lib/python3.7/dist-packages/kaggle/api/kaggle_api_extended.py\", line 166, in authenticate\n","    self.config_file, self.config_dir))\n","OSError: Could not find kaggle.json. Make sure it's located in /root/.kaggle. Or use the environment method.\n"]}],"source":["#Loading dataset from kaggle \n","! kaggle datasets download akrsnv/lions-and-tigers\n"]},{"cell_type":"code","source":["from google.colab import drive\n","drive.mount('/content/drive')"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"fusH5MlBnztN","executionInfo":{"status":"ok","timestamp":1648640379520,"user_tz":-330,"elapsed":29108,"user":{"displayName":"Akash Sri","userId":"07595179456817660778"}},"outputId":"8dc82e75-71b8-4ff7-e1bc-adba24140310"},"execution_count":1,"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /content/drive\n"]}]},{"cell_type":"code","source":[""],"metadata":{"id":"iLI8ZSYbgiSG"},"execution_count":null,"outputs":[]}]}